### ISSUE TITLE
导航栏图片背景与背景色不协调

### ISSUE THREAD

**Issue by keob** [china-net-community/OfficialWebsite#1]
导航栏图片背景与背景色不协调

**Comment by lfzm** [comment]
@keob 如果有什么高见可以提 PR 哦，我们很欢迎

**Comment by keob** [comment]
抱歉不会pr只是一个写代码的，一般logo是用的ico格式，会不会好点。

**Comment by lfzm** [comment]
不会提PR，你可以把问题详细列一下，我们一点一点处理。谢谢你的意见

其实 `PR` 很简单的，github 现在有中文的[帮助文档](https://help.github.com/cn)了

**Comment by keob** [comment]
我以为你说的是视频剪辑😊😊
